% BUILD_LABELMAP_MEX  Build the mj_labelmap_mex MEX file.
%
%   Run from the tools/ directory, or it will cd there automatically.

thisDir = fileparts(mfilename('fullpath'));
cd(thisDir);

% Paths from win64.mk / setupBuild / install.m
srcPath   = fullfile(thisDir, '..', 'src');
outDir    = fullfile(thisDir, '..', 'blocks');
mjPath    = fullfile(thisDir, '..', 'lib', 'win64', 'mujoco');

glfwIncPath      = getpref('mujoco', 'glfwIncPath');
glfwImportLibPath = getpref('mujoco', 'glfwImportLibPath');

srcCommon = fullfile(srcPath, 'mj.cpp');
srcFile   = fullfile(srcPath, 'mj_labelmap_mex.cpp');

incFlags = { ...
    ['-I' fullfile(mjPath, 'include', 'mujoco')], ...
    ['-I' fullfile(mjPath, 'include')], ...
    ['-I' srcPath], ...
    ['-I' glfwIncPath] ...
};

linkObjs = { ...
    fullfile(glfwImportLibPath, 'glfw3dll.lib'), ...
    fullfile(mjPath, 'lib', 'mujoco.lib') ...
};

fprintf('Building mj_labelmap_mex...\n');
fprintf('  Source:  %s\n', srcFile);
fprintf('  Common:  %s\n', srcCommon);
fprintf('  Output:  %s\n', outDir);

mex(srcCommon, srcFile, ...
    incFlags{:}, ...
    linkObjs{:}, ...
    'COMPFLAGS=/EHsc /std:c++17', ...
    '-g', ...
    '-outdir', outDir, ...
    '-output', 'mj_labelmap_mex');

fprintf('Build complete: %s\n', fullfile(outDir, ['mj_labelmap_mex.' mexext]));
